schema_path: https://raw.githubusercontent.com/matumot/xafs-schema/main/draft/20221212/xafs-schema.json
#schema_path: ./draft/20221212/xafs-schema.json
#schema_path: ./draft/202221212/xafs-schema-none-ok.json
